language: go

sudo: false

install:
  - go get github.com/tools/godep
  - godep restore
  # for test coverage
  - go get github.com/axw/gocov/gocov github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - export PATH=$PATH:$GOPATH/bin

script:
  - go test
  - go build -v
  - gocov test ./... -covermode count > gocov.json
  - goveralls -service=travis-ci

  - cd maya-cli
  - go build -v
  - cd ..

notifications:
  email: false
