language: go

sudo: false

install:
  - go get github.com/tools/godep
  - godep restore
  # for test coverage
  - go get github.com/axw/gocov/gocov github.com/mattn/goveralls
  - go get github.com/golang/tools/cmd/cover
  - export PATH=$PATH:$GOPATH/bin

script:
  - go test
  - go build -v
  - gocov test ./... -covermode count > gocov.json
  - goveralls -service=travis-ci -gocovdata gocov.json

notifications:
  email: false
